// src/app/components/query-builder/query-builder.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject, takeUntil } from 'rxjs';
import { QueryBuilderService } from '../../services/query-builder.service';
import { 
  TableMetadata, 
  QueryBuilderState, 
  SqlQueryResponse, 
  QueryExecutionResult 
} from '../../models/query-builder.types';

@Component({
  selector: 'app-query-builder',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="min-h-screen bg-neutral-50 p-6">
      <div class="max-w-7xl mx-auto">
        <!-- Header -->
        <div class="mb-8">
          <h1 class="text-3xl font-bold text-neutral-800 mb-2">Basic Query Builder</h1>
          <p class="text-neutral-600">Select tables and columns to build your SQL query</p>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <!-- Query Builder Panel -->
          <div class="lg:col-span-2 space-y-6">
            <!-- Table Selection -->
            <div class="bg-white rounded-lg shadow-sm border border-neutral-200 p-6">
              <h2 class="text-lg font-semibold text-neutral-800 mb-4 flex items-center">
                <svg class="w-5 h-5 mr-2 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14-6H5m14 12H5"></path>
                </svg>
                Select Tables
              </h2>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-4" *ngIf="!isLoading; else loadingSkeleton">
                <div *ngFor="let table of tables" 
                     class="border border-neutral-200 rounded-lg p-4 hover:bg-neutral-50 cursor-pointer transition-colors"
                     [class.bg-blue-50]="isTableSelected(table.name)"
                     [class.border-blue-300]="isTableSelected(table.name)"
                     (click)="toggleTable(table.name)">
                  <div class="flex items-center space-x-3">
                    <input 
                      type="checkbox" 
                      [checked]="isTableSelected(table.name)"
                      (change)="toggleTable(table.name)"
                      class="w-4 h-4 text-blue-600 border-neutral-300 rounded focus:ring-blue-500">
                    <div>
                      <div class="font-medium text-neutral-800">{{table.name}}</div>
                      <div class="text-sm text-neutral-500">{{table.recordCount}} records</div>
                    </div>
                  </div>
                </div>
              </div>

              <ng-template #loadingSkeleton>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div *ngFor="let i of [1,2,3,4]" class="h-16 bg-neutral-200 rounded-lg animate-pulse"></div>
                </div>
              </ng-template>
            </div>

            <!-- Column Selection -->
            <div *ngIf="queryState.selectedTables.length > 0" 
                 class="bg-white rounded-lg shadow-sm border border-neutral-200 p-6">
              <h2 class="text-lg font-semibold text-neutral-800 mb-4 flex items-center">
                <svg class="w-5 h-5 mr-2 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 002-2M9 7a2 2 0 012 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 002-2"></path>
                </svg>
                Select Columns
              </h2>
              
              <div *ngFor="let tableName of queryState.selectedTables" class="mb-6 last:mb-0">
                <h3 class="text-sm font-medium text-neutral-700 mb-3">{{tableName}}</h3>
                <div class="grid grid-cols-2 md:grid-cols-3 gap-2">
                  <label *ngFor="let column of getTableColumns(tableName)" 
                         class="flex items-center text-sm cursor-pointer hover:bg-neutral-50 p-2 rounded">
                    <input 
                      type="checkbox" 
                      [checked]="isColumnSelected(tableName, column.name)"
                      (change)="toggleColumn(tableName, column.name)"
                      class="w-3 h-3 text-blue-600 border-neutral-300 rounded focus:ring-blue-500 mr-2">
                    <span class="text-neutral-700">{{column.name}}</span>
                    <span class="ml-1 text-xs text-neutral-400">({{column.type}})</span>
                  </label>
                </div>
              </div>
            </div>

            <!-- Natural Language Input -->
            <div class="bg-white rounded-lg shadow-sm border border-neutral-200 p-6">
              <h2 class="text-lg font-semibold text-neutral-800 mb-4 flex items-center">
                <svg class="w-5 h-5 mr-2 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-3.582 8-8 8a8.955 8.955 0 01-2.304-.306l-4.844 1.27a1 1 0 01-1.29-1.29l1.27-4.844A8.955 8.955 0 013 12a8 8 0 018-8c4.418 0 8 3.582 8 8z"></path>
                </svg>
                Natural Language Query
              </h2>
              <textarea 
                [(ngModel)]="naturalLanguageQuery"
                placeholder="Describe what you want to query in plain English..."
                class="w-full h-24 px-3 py-2 border border-neutral-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
              ></textarea>
            </div>

            <!-- Action Buttons -->
            <div class="flex justify-between items-center">
              <button 
                (click)="generateQuery()"
                [disabled]="isGenerating || (queryState.selectedTables.length === 0 && !naturalLanguageQuery.trim())"
                class="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:bg-neutral-300 disabled:cursor-not-allowed flex items-center space-x-2">
                <svg *ngIf="!isGenerating" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                </svg>
                <div *ngIf="isGenerating" class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                <span>{{isGenerating ? 'Generating...' : 'Generate Query'}}</span>
              </button>

              <div class="flex space-x-2">
                <button 
                  (click)="executeQuery()"
                  [disabled]="isExecuting || !generatedQuery?.sql"
                  class="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:bg-neutral-300 disabled:cursor-not-allowed flex items-center space-x-2">
                  <svg *ngIf="!isExecuting" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h1m4 0h1M15 21v-3a6 6 0 00-6 0v3"></path>
                  </svg>
                  <div *ngIf="isExecuting" class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                  <span>{{isExecuting ? 'Executing...' : 'Execute'}}</span>
                </button>

                <button 
                  (click)="resetQuery()"
                  class="px-4 py-2 border border-neutral-300 text-neutral-700 rounded-md hover:bg-neutral-50">
                  Reset
                </button>
              </div>
            </div>
          </div>

          <!-- Results Panel -->
          <div class="space-y-6">
            <!-- Generated Query -->
            <div *ngIf="generatedQuery" class="bg-white rounded-lg shadow-sm border border-neutral-200 p-6">
              <div class="flex justify-between items-center mb-4">
                <h3 class="text-sm font-medium text-neutral-800">Generated SQL</h3>
                <button 
                  (click)="copyToClipboard(generatedQuery.sql)"
                  class="text-xs px-2 py-1 border border-neutral-300 rounded hover:bg-neutral-50">
                  Copy
                </button>
              </div>
              <pre class="text-xs bg-neutral-900 text-green-400 p-3 rounded overflow-x-auto">{{generatedQuery.sql}}</pre>
              <div *ngIf="generatedQuery.naturalLanguage" 
                   class="mt-3 p-3 bg-blue-50 border border-blue-200 rounded">
                <p class="text-xs text-blue-800">{{generatedQuery.naturalLanguage}}</p>
              </div>
            </div>

            <!-- Query Results -->
            <div *ngIf="queryResults" class="bg-white rounded-lg shadow-sm border border-neutral-200 p-6">
              <div class="flex justify-between items-center mb-4">
                <h3 class="text-sm font-medium text-neutral-800">Results ({{queryResults.totalCount}} rows)</h3>
                <button 
                  (click)="exportResults('csv')"
                  class="text-xs px-2 py-1 border border-neutral-300 rounded hover:bg-neutral-50 flex items-center space-x-1">
                  <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                  </svg>
                  <span>Export CSV</span>
                </button>
              </div>
              <div class="overflow-x-auto">
                <table class="min-w-full">
                  <thead>
                    <tr class="border-b border-neutral-200">
                      <th *ngFor="let column of queryResults.columns" 
                          class="text-left text-xs font-medium text-neutral-500 uppercase tracking-wider py-2">
                        {{column}}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr *ngFor="let row of queryResults.rows.slice(0, 50); let i = index" 
                        [class.bg-neutral-50]="i % 2 === 1"
                        class="border-b border-neutral-100">
                      <td *ngFor="let column of queryResults.columns" 
                          class="text-xs text-neutral-900 py-2">
                        {{row[column] || '—'}}
                      </td>
                    </tr>
                  </tbody>
                </table>
                <p *ngIf="queryResults.rows.length > 50" 
                   class="text-xs text-neutral-500 text-center mt-2">
                  Showing first 50 of {{queryResults.totalCount}} results
                </p>
              </div>
              <div class="mt-3 text-xs text-neutral-500">
                Execution time: {{queryResults.executionTime}}ms
              </div>
            </div>

            <!-- Error Display -->
            <div *ngIf="errorMessage" class="bg-red-50 border border-red-200 rounded-lg p-4">
              <div class="flex items-center">
                <svg class="w-4 h-4 text-red-400 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                <p class="text-sm text-red-800">{{errorMessage}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: []
})
export class QueryBuilderComponent implements OnInit, OnDestroy {
  private destroy$ = new Subject<void>();
  
  tables: TableMetadata[] = [];
  queryState: QueryBuilderState = {
    selectedTables: [],
    selectedColumns: {},
    aggregationColumns: [],
    groupByColumns: [],
    filterConditions: [],
    sortColumns: [],
    limit: undefined,
    distinct: false
  };
  
  naturalLanguageQuery = '';
  generatedQuery: SqlQueryResponse | null = null;
  queryResults: QueryExecutionResult | null = null;
  errorMessage = '';
  
  isLoading = false;
  isGenerating = false;
  isExecuting = false;

  constructor(private queryBuilderService: QueryBuilderService) {}

  ngOnInit() {
    this.loadTables();
    this.queryBuilderService.queryState$
      .pipe(takeUntil(this.destroy$))
      .subscribe(state => this.queryState = state);
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  loadTables() {
    this.isLoading = true;
    this.queryBuilderService.getTableMetadata()
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (data) => {
          this.tables = data.tables;
          this.isLoading = false;
        },
        error: (error) => {
          this.errorMessage = 'Failed to load table metadata';
          this.isLoading = false;
        }
      });
  }

  isTableSelected(tableName: string): boolean {
    return this.queryState.selectedTables.includes(tableName);
  }

  toggleTable(tableName: string) {
    const isSelected = this.isTableSelected(tableName);
    let newSelectedTables: string[];
    let newSelectedColumns = { ...this.queryState.selectedColumns };

    if (isSelected) {
      newSelectedTables = this.queryState.selectedTables.filter(t => t !== tableName);
      delete newSelectedColumns[tableName];
    } else {
      newSelectedTables = [...this.queryState.selectedTables, tableName];
    }

    this.queryBuilderService.updateQueryState({
      selectedTables: newSelectedTables,
      selectedColumns: newSelectedColumns
    });
  }

  getTableColumns(tableName: string) {
    const table = this.tables.find(t => t.name === tableName);
    return table?.columns || [];
  }

  isColumnSelected(tableName: string, columnName: string): boolean {
    return (this.queryState.selectedColumns[tableName] || []).includes(columnName);
  }

  toggleColumn(tableName: string, columnName: string) {
    const currentColumns = this.queryState.selectedColumns[tableName] || [];
    const isSelected = currentColumns.includes(columnName);
    
    const newColumns = isSelected
      ? currentColumns.filter(c => c !== columnName)
      : [...currentColumns, columnName];

    this.queryBuilderService.updateQueryState({
      selectedColumns: {
        ...this.queryState.selectedColumns,
        [tableName]: newColumns
      }
    });
  }

  generateQuery() {
    this.isGenerating = true;
    this.errorMessage = '';
    
    const request = {
      naturalLanguageQuery: this.naturalLanguageQuery || this.buildNaturalLanguageFromState(),
      ...this.queryState
    };

    this.queryBuilderService.generateSqlQuery(request)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (response) => {
          if (response.error) {
            this.errorMessage = response.error;
          } else {
            this.generatedQuery = response;
          }
          this.isGenerating = false;
        },
        error: (error) => {
          this.errorMessage = 'Failed to generate SQL query';
          this.isGenerating = false;
        }
      });
  }

  executeQuery() {
    if (!this.generatedQuery?.sql) return;
    
    this.isExecuting = true;
    this.errorMessage = '';

    this.queryBuilderService.executeQuery(this.generatedQuery.sql)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (results) => {
          this.queryResults = results;
          this.isExecuting = false;
        },
        error: (error) => {
          this.errorMessage = 'Failed to execute query';
          this.isExecuting = false;
        }
      });
  }

  resetQuery() {
    this.queryBuilderService.resetQueryState();
    this.naturalLanguageQuery = '';
    this.generatedQuery = null;
    this.queryResults = null;
    this.errorMessage = '';
  }

  exportResults(format: string) {
    if (!this.queryResults) return;
    
    this.queryBuilderService.exportResults(format, this.queryResults)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (data) => {
          if (format === 'csv') {
            const blob = new Blob([data], { type: 'text/csv' });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'query-results.csv';
            a.click();
            window.URL.revokeObjectURL(url);
          }
        },
        error: (error) => {
          this.errorMessage = 'Failed to export results';
        }
      });
  }

  copyToClipboard(text: string) {
    navigator.clipboard.writeText(text).then(() => {
      // Could show a toast notification here
    }).catch(() => {
      this.errorMessage = 'Failed to copy to clipboard';
    });
  }

  private buildNaturalLanguageFromState(): string {
    if (this.queryState.selectedTables.length === 0) return '';
    
    const columnCount = Object.values(this.queryState.selectedColumns).flat().length;
    return `Get ${columnCount} columns from ${this.queryState.selectedTables.join(', ')} tables`;
  }
}

// client/src/pages/query-builder.tsx
import { useState, useEffect } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { 
  Database, 
  Table as TableIcon, 
  Columns, 
  Calculator, 
  Wand2, 
  Play, 
  RotateCcw, 
  Copy, 
  Download,
  FileSpreadsheet,
  Settings,
  HelpCircle 
} from "lucide-react";
import type { QueryBuilderState, SqlQueryResponse, QueryExecutionResult } from "@shared/schema";

interface TableMetadata {
  name: string;
  recordCount: number;
  columns: Array<{
    name: string;
    type: string;
  }>;
}

export default function QueryBuilder() {
  const { toast } = useToast();
  const [queryState, setQueryState] = useState<QueryBuilderState>({
    selectedTables: [],
    selectedColumns: {},
    aggregationFunction: undefined,
    targetColumn: undefined,
    groupByColumns: [],
  });
  
  const [generatedQuery, setGeneratedQuery] = useState<SqlQueryResponse | null>(null);
  const [queryResults, setQueryResults] = useState<QueryExecutionResult | null>(null);
  const [naturalLanguagePreview, setNaturalLanguagePreview] = useState<string>("");

  // Fetch table metadata
  const { data: tableData, isLoading: tablesLoading } = useQuery<{ tables: TableMetadata[] }>({
    queryKey: ["/api/tables"],
  });

  // Generate SQL query mutation
  const generateQueryMutation = useMutation({
    mutationFn: async (request: any) => {
      const response = await apiRequest("POST", "/api/generate-query", request);
      return response.json();
    },
    onSuccess: (data: SqlQueryResponse) => {
      if (data.error) {
        toast({
          title: "Error",
          description: data.error,
          variant: "destructive",
        });
      } else {
        setGeneratedQuery(data);
        toast({
          title: "Success",
          description: "SQL query generated successfully",
        });
      }
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to generate SQL query",
        variant: "destructive",
      });
    },
  });

  // Execute query mutation
  const executeQueryMutation = useMutation({
    mutationFn: async (sql: string) => {
      const response = await apiRequest("POST", "/api/execute-query", { sql });
      return response.json();
    },
    onSuccess: (data: QueryExecutionResult) => {
      setQueryResults(data);
      toast({
        title: "Success",
        description: `Query executed successfully. ${data.totalCount} rows returned.`,
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to execute query",
        variant: "destructive",
      });
    },
  });

  // Update natural language preview
  useEffect(() => {
    if (queryState.selectedTables.length > 0) {
      const tableNames = queryState.selectedTables.join(", ");
      const columnCount = Object.values(queryState.selectedColumns).flat().length;
      const aggregation = queryState.aggregationFunction || "SELECT";
      const groupBy = queryState.groupByColumns.length > 0 ? ` grouped by ${queryState.groupByColumns.join(", ")}` : "";
      
      setNaturalLanguagePreview(
        `${aggregation} data from ${tableNames} table${queryState.selectedTables.length > 1 ? "s" : ""} with ${columnCount} column${columnCount !== 1 ? "s" : ""}${groupBy}.`
      );
    } else {
      setNaturalLanguagePreview("Select tables and columns to see query description.");
    }
  }, [queryState]);

  const handleTableSelection = (tableName: string, checked: boolean) => {
    setQueryState(prev => {
      const newSelectedTables = checked 
        ? [...prev.selectedTables, tableName]
        : prev.selectedTables.filter(t => t !== tableName);
      
      const newSelectedColumns = { ...prev.selectedColumns };
      if (!checked) {
        delete newSelectedColumns[tableName];
      }
      
      return {
        ...prev,
        selectedTables: newSelectedTables,
        selectedColumns: newSelectedColumns,
      };
    });
  };

  const handleColumnSelection = (tableName: string, columnName: string, checked: boolean) => {
    setQueryState(prev => ({
      ...prev,
      selectedColumns: {
        ...prev.selectedColumns,
        [tableName]: checked
          ? [...(prev.selectedColumns[tableName] || []), columnName]
          : (prev.selectedColumns[tableName] || []).filter(c => c !== columnName),
      },
    }));
  };

  const handleGroupByToggle = (columnName: string) => {
    setQueryState(prev => ({
      ...prev,
      groupByColumns: prev.groupByColumns.includes(columnName)
        ? prev.groupByColumns.filter(c => c !== columnName)
        : [...prev.groupByColumns, columnName],
    }));
  };

  const handleGenerateQuery = () => {
    if (queryState.selectedTables.length === 0) {
      toast({
        title: "Error",
        description: "Please select at least one table",
        variant: "destructive",
      });
      return;
    }

    const request = {
      naturalLanguageQuery: naturalLanguagePreview,
      ...queryState,
    };

    generateQueryMutation.mutate(request);
  };

  const handleExecuteQuery = () => {
    if (!generatedQuery?.sql) {
      toast({
        title: "Error",
        description: "Please generate a query first",
        variant: "destructive",
      });
      return;
    }

    executeQueryMutation.mutate(generatedQuery.sql);
  };

  const handleReset = () => {
    setQueryState({
      selectedTables: [],
      selectedColumns: {},
      aggregationFunction: undefined,
      targetColumn: undefined,
      groupByColumns: [],
    });
    setGeneratedQuery(null);
    setQueryResults(null);
  };

  const copyToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      toast({
        title: "Success",
        description: "Copied to clipboard",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to copy to clipboard",
        variant: "destructive",
      });
    }
  };

  const exportResults = async (format: string) => {
    if (!queryResults) return;

    try {
      const response = await apiRequest("POST", "/api/export-results", {
        format,
        data: queryResults,
      });

      if (format === "csv") {
        const blob = new Blob([await response.text()], { type: "text/csv" });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "query-results.csv";
        a.click();
        window.URL.revokeObjectURL(url);
      }

      toast({
        title: "Success",
        description: `Results exported as ${format.toUpperCase()}`,
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to export results",
        variant: "destructive",
      });
    }
  };

  const availableColumns = queryState.selectedTables.flatMap(tableName => {
    const table = tableData?.tables.find(t => t.name === tableName);
    return table?.columns.map(col => `${tableName}.${col.name}`) || [];
  });

  return (
    <div className="min-h-screen bg-neutral-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-neutral-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-3">
              <Database className="text-primary text-xl" />
              <h1 className="text-xl font-semibold text-neutral-800">SQL Query Builder</h1>
            </div>
            <div className="flex items-center space-x-4">
              <Button variant="ghost" size="sm">
                <HelpCircle className="h-4 w-4" />
              </Button>
              <Button variant="ghost" size="sm">
                <Settings className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Query Builder */}
          <div className="lg:col-span-2 space-y-6">
            {/* Table Selection */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <TableIcon className="text-primary mr-2" />
                  Select Tables
                </CardTitle>
                <p className="text-sm text-neutral-600">Choose the database tables you want to query</p>
              </CardHeader>
              <CardContent>
                {tablesLoading ? (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {[...Array(4)].map((_, i) => (
                      <Skeleton key={i} className="h-16 w-full" />
                    ))}
                  </div>
                ) : (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {tableData?.tables.map((table) => (
                      <label key={table.name} className="flex items-center p-3 border border-neutral-200 rounded-lg hover:bg-neutral-50 cursor-pointer transition-colors">
                        <Checkbox
                          checked={queryState.selectedTables.includes(table.name)}
                          onCheckedChange={(checked) => handleTableSelection(table.name, checked as boolean)}
                          className="w-4 h-4"
                        />
                        <div className="ml-3">
                          <div className="text-sm font-medium text-neutral-800">{table.name}</div>
                          <div className="text-xs text-neutral-500">{table.recordCount} records</div>
                        </div>
                      </label>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Column Selection */}
            {queryState.selectedTables.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center">
                    <Columns className="text-primary mr-2" />
                    Select Columns
                  </CardTitle>
                  <p className="text-sm text-neutral-600">Choose columns from selected tables</p>
                </CardHeader>
                <CardContent>
                  {queryState.selectedTables.map((tableName) => {
                    const table = tableData?.tables.find(t => t.name === tableName);
                    if (!table) return null;

                    return (
                      <div key={tableName} className="mb-6 last:mb-0">
                        <h3 className="text-sm font-medium text-neutral-700 mb-3 flex items-center">
                          <TableIcon className="text-neutral-400 mr-2 text-xs" />
                          {tableName}
                        </h3>
                        <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
                          {table.columns.map((column) => (
                            <label key={column.name} className="flex items-center text-sm">
                              <Checkbox
                                checked={(queryState.selectedColumns[tableName] || []).includes(column.name)}
                                onCheckedChange={(checked) => handleColumnSelection(tableName, column.name, checked as boolean)}
                                className="w-3 h-3"
                              />
                              <span className="ml-2 text-neutral-700">{column.name}</span>
                              <span className="ml-1 text-xs text-neutral-400">({column.type})</span>
                            </label>
                          ))}
                        </div>
                      </div>
                    );
                  })}
                </CardContent>
              </Card>
            )}

            {/* Aggregation Functions */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Calculator className="text-primary mr-2" />
                  Aggregation Functions
                </CardTitle>
                <p className="text-sm text-neutral-600">Apply mathematical operations to your data</p>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-2">Primary Function</label>
                    <Select
                      value={queryState.aggregationFunction || ""}
                      onValueChange={(value) => setQueryState(prev => ({ ...prev, aggregationFunction: value }))}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select function..." />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="SELECT">SELECT</SelectItem>
                        <SelectItem value="COUNT">COUNT</SelectItem>
                        <SelectItem value="SUM">SUM</SelectItem>
                        <SelectItem value="AVG">AVG</SelectItem>
                        <SelectItem value="MAX">MAX</SelectItem>
                        <SelectItem value="MIN">MIN</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-2">Target Column</label>
                    <Select
                      value={queryState.targetColumn || ""}
                      onValueChange={(value) => setQueryState(prev => ({ ...prev, targetColumn: value }))}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select column..." />
                      </SelectTrigger>
                      <SelectContent>
                        {availableColumns.map((column) => (
                          <SelectItem key={column} value={column}>{column}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="mt-6">
                  <label className="block text-sm font-medium text-neutral-700 mb-2">Group By</label>
                  <div className="flex flex-wrap gap-2">
                    {availableColumns.map((column) => (
                      <Badge
                        key={column}
                        variant={queryState.groupByColumns.includes(column) ? "default" : "outline"}
                        className="cursor-pointer"
                        onClick={() => handleGroupByToggle(column)}
                      >
                        {column}
                      </Badge>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Action Buttons */}
            <div className="flex justify-between items-center">
              <Button 
                onClick={handleGenerateQuery}
                disabled={generateQueryMutation.isPending || queryState.selectedTables.length === 0}
                className="px-6 py-3 font-medium"
              >
                <Wand2 className="mr-2 h-4 w-4" />
                {generateQueryMutation.isPending ? "Generating..." : "Generate SQL Query"}
              </Button>
              <Button variant="ghost" onClick={handleReset}>
                <RotateCcw className="mr-1 h-4 w-4" />
                Reset
              </Button>
            </div>
          </div>

          {/* Query Preview */}
          <div className="space-y-6">
            {/* Natural Language Preview */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Database className="text-primary mr-2" />
                  Query Description
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="bg-neutral-50 border border-neutral-200 rounded-lg p-4">
                  <p className="text-sm text-neutral-700 leading-relaxed">
                    {naturalLanguagePreview}
                  </p>
                </div>
              </CardContent>
            </Card>

            {/* Generated SQL */}
            {generatedQuery && (
              <Card>
                <CardHeader>
                  <div className="flex justify-between items-center">
                    <CardTitle className="flex items-center">
                      <Database className="text-primary mr-2" />
                      Generated SQL
                    </CardTitle>
                    <div className="flex space-x-2">
                      <Button 
                        variant="ghost" 
                        size="sm"
                        onClick={() => copyToClipboard(generatedQuery.sql)}
                      >
                        <Copy className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="bg-neutral-900 rounded-lg p-4 overflow-x-auto">
                    <pre className="text-sm text-green-400 font-mono">
                      <code>{generatedQuery.sql}</code>
                    </pre>
                  </div>
                  {generatedQuery.naturalLanguage && (
                    <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
                      <p className="text-sm text-blue-800">{generatedQuery.naturalLanguage}</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            )}

            {/* Execute Button */}
            {generatedQuery && (
              <Button 
                className="w-full bg-green-600 hover:bg-green-700"
                onClick={handleExecuteQuery}
                disabled={executeQueryMutation.isPending}
              >
                <Play className="mr-2 h-4 w-4" />
                {executeQueryMutation.isPending ? "Executing..." : "Execute Query"}
              </Button>
            )}

            {/* Loading State */}
            {(generateQueryMutation.isPending || executeQueryMutation.isPending) && (
              <Card>
                <CardContent className="pt-6">
                  <div className="flex items-center justify-center">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
                    <span className="ml-3 text-neutral-600">
                      {generateQueryMutation.isPending ? "Generating query..." : "Executing query..."}
                    </span>
                  </div>
                </CardContent>
              </Card>
            )}
          </div>
        </div>

        {/* Query Results */}
        {queryResults && (
          <div className="mt-8">
            <Card>
              <CardHeader>
                <div className="flex justify-between items-center">
                  <CardTitle className="flex items-center">
                    <TableIcon className="text-primary mr-2" />
                    Query Results
                    <span className="ml-2 text-sm font-normal text-neutral-500">
                      ({queryResults.totalCount} rows)
                    </span>
                  </CardTitle>
                  <div className="flex space-x-2">
                    <Button 
                      variant="outline" 
                      size="sm"
                      onClick={() => exportResults("csv")}
                    >
                      <Download className="mr-1 h-4 w-4" />
                      Export CSV
                    </Button>
                    <Button 
                      variant="outline" 
                      size="sm"
                      onClick={() => exportResults("excel")}
                    >
                      <FileSpreadsheet className="mr-1 h-4 w-4" />
                      Export Excel
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        {queryResults.columns.map((column) => (
                          <TableHead key={column} className="text-xs font-medium text-neutral-500 uppercase tracking-wider">
                            {column.replace(/_/g, " ")}
                          </TableHead>
                        ))}
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {queryResults.rows.map((row, index) => (
                        <TableRow key={index} className="hover:bg-neutral-50">
                          {queryResults.columns.map((column) => (
                            <TableCell key={column} className="text-sm text-neutral-900">
                              {row[column]?.toString() || ""}
                            </TableCell>
                          ))}
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
                <div className="mt-4 text-sm text-neutral-500">
                  Execution time: {queryResults.executionTime}ms
                </div>
              </CardContent>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
}
